### ISSUE TITLE
SteamOS Session permanently changes the display resolution for my normal desktop

### ISSUE THREAD

**Issue by audreytoskin** [negativo17/steam#2]
Trying out the steamos-session package has been kind of a disaster :(

**My system setup**
- OS: Fedora 24 (64-bit)
- Graphics: Nvidia GeForce 9600 GT
  - proprietary drivers from RPM Fusion: `akmod-nvidia-340xx`
  - other libraries: `libtxc_dxtn`, `libva-utils`, `libva-vdpau-driver`, `vdpauinfo`, `xorg-x11-drv-nvidia-340xx-libs.i686`
- Steam packages: `steam`, `steamos-session`, `steamos-modeswitch-inhibitor.i686`
## It basically worked out fine, at first

Or at least, it worked about as well as I might have expected.

I installed steamos-session and the modeswitch inhibitor, as instructed [on the blog page for your repo](http://negativo17.org/steam/). Selecting the SteamOS session and logging into the SteamOS user account didn't work -- I entered the password, and it showed a blank black screen. After a few minutes of this, I started hitting random keys to see if something would happen; when I hit <kbd>Esc</kbd>, it returned to the GDM login screen. Selecting the SteamOS session and logging into my normal user (instead of GNOME) did work, though: One of my games ran well, and maybe even benefited from the saved RAM of not running a full desktop environment in the background. The rest of my games ran very, very slowly -- but I believe that's an ongoing issue for Steam in "Big Picture" mode, and not necessarily a problem with the steamos-session package.

So okay, I probably won't be using the SteamOS session most of the time, but it was interesting to see.
## Then the graphical problems appeared

SteamOS doesn't have a way to log out normally, so I rebooted.

My monitor is supposed to run at 1080p. When I came back to the GDM login screen, it looked like the screen resolution had been turned down to 720p, possibly lower. All text, icons, and images are bigger, and a little blurry. The GNOME top bar also now displays the accessibility icon, and the drop-down menu shows that the "Large Text" feature is enabled -- so I guess I'm not entirely sure if the display resolution is actually different, or if it's just the GNOME Accessibility scaling everything up, or maybe _both_.
## Ways that I have tried to fix the problem.

I tried turning off Large Text in the Accessibility settings. Clicking to turn off Large text from the top bar icon does nothing; Large Text is always enabled. When I go to GNOME Settings > Universal Access > Large Text, I can click the switch, and the little slider graphic switches to "Off," but the top bar icon still shows Large Text as enabled, and the text, icons, and images on my screen are still blurry.

I tried making sure my display settings were correct: I opened GNOME Settings > Displays, clicked on the box for my monitor (I have only have one), but it was already set to 1920 × 1080. Turning it down to a lower resolution, clicking apply, and then turning it back up to 1080p hasn't helped.

I tried opening Nvidia X Server Settings > X Server Display Configuration, and manually setting the resolution to the correct value (instead of just "auto"). No effect.

I tried logging back into SteamOS Session and looking for display resolution under the Settings menu. However, SteamOS Session doesn't let you actually change the resolution, only enlarge or shrink the display area on screen.

I tried launching Steam in Big Picture mode from GNOME Shell. Before trying SteamOS Session, I would normally launch Steam in desktop mode, and had set Big Picture Mode to run in a small window, because my graphics card is kinda old, and Steam BPM doesn't run very well. But now I tried setting Steam BPM back up to 1080p and full-screen. No effect.

It's funny, Steam in desktop mode actually renders at the correct resolution. Everything else has this rendering problem, though.

I tried uninstalling and reinstalling all the steam packages and my graphics driver. No effect.

Rebooting, praying, and doing a rain dance between each of these steps hasn't helped much either.

I don't get it. I'd rather not have to reinstall Fedora again, but my desktop is kind of unpleasant to look at right now.

**Comment by audreytoskin** [comment]
...Okay, so after like 3 hours of trying to find and solve a problem with my display resolution, I thought to try investigating the GNOME Accessibility settings again.

I went to GNOME Tweak Tool > Fonts. And it turns out the Scaling Factor had been turned up to 1.5 for some reason. I turned it back down to 1.0, logged out, and logged back in. The GDM login screen still shows Large Text enabled, and I cannot disable it in GDM, but when I log back into GNOME, everything renders the way it should again, and the Accessibility icon has disappeared from the top bar. So, I guess, hurray!

Games change various display resolution settings all the time. It's bizarre installing steamos-session would change the accessibility / text scaling settings.

**Comment by audreytoskin** [comment]
I tried to disable text scaling at the system-wide level by running `sudo gnome-tweak-tool` and then going to the Fonts tab and turning the Scaling Factor down to 1.0 again. That didn't affect the rendering of the GDM login screen, but at least it's only for the login screen.

**Comment by scaronni** [comment]
Package being reworked from scratch.
