### ISSUE TITLE
Civ6 fails due to missing library

### ISSUE THREAD

**Issue by gbraad** [negativo17/steam#3]
```
./Civ6: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

If more info needed, just let me know...

**Comment by scaronni** [comment]
Which steam package version are you using? The latest one with the new mechanism for preferring host libraries or the old one with support for running Steam without the Ubuntu Runtime?

Do you have the `compat-openssl` installed as part of the Spotify package?

If any of those is true or you're not sure, just install all updates pending, reboot and tell me if it's still happening.

**Comment by gbraad** [comment]
I just noticed there was a new version. I will try it out ASAP and let you know.
No Spotify installed...

**Comment by gbraad** [comment]
`steam-1.0.0.54-7.fc25.i686`

```
steam runtime beta 2016-12-05
```

**Comment by gbraad** [comment]
It works now...
