### ISSUE TITLE
steam repo sync issue

### ISSUE THREAD

**Issue by tla2k12** [negativo17/steam#4]
Hi, tried out the steam repo but it doesn't sync. I guess this is because I am not using a supported OS (fedora 26 rawhide)? If this is the reason, may be worth adding a supported OS table to the README? If it's something else, happy to help work out what the issue is.

Current OS:
```
$ cat /etc/system-release
Fedora release 26 (Twenty Six)
```

Adding the repo seems fine:
```
$ sudo dnf config-manager --add-repo=http://negativo17.org/repos/fedora-steam.repo
Adding repo from: http://negativo17.org/repos/fedora-steam.repo
```

But trying an install has a sync issue:
```
$ sudo dnf install steam
Failed to synchronize cache for repo 'fedora-steam', disabling.
Last metadata expiration check: 1:27:46 ago on Fri Apr 14 18:24:28 2017.
No package steam available.
Error: Unable to find a match
```

A forced refresh doesn't help:
```
$ sudo dnf install --refresh steam
Failed to synchronize cache for repo 'fedora-steam', disabling.
Last metadata expiration check: 0:00:00 ago on Fri Apr 14 19:52:56 2017.
No package steam available.
Error: Unable to find a match
$
```

**Comment by scaronni** [comment]
I forgot to push the repository, sorry. New upload coming in a few minutes with the Fedora 26 branch.
