### ISSUE TITLE
Steam OS session changes Scaling Factor, Background Image and Desktop Icons for ALL users

### ISSUE THREAD

**Issue by abc-mikey** [negativo17/steam#5]
Installing this changes for ALL users:
 
* Scaling Factor to 1.5
* background image to the steam OS logo 
* adds icons such as mountable drives to desktop

It may make other changes but these are the ones that I have noticed.

The first one is a duplicate of #2. 

```
Name         : steamos-session
Version      : 1.34
Release      : 1.fc27
Arch         : noarch
Größe        : 22 k
Quelle       : steamos-compositor-1.34-1.fc27.src.rpm
Paketquelle  : fedora-steam
Zusammenfass : SteamOS desktop session
URL          : http://store.steampowered.com/steamos/
Lizenz       : BSD
```

Fedora release 27 (Twenty Seven)

**Comment by scaronni** [comment]
Sorry for the late reply. Package is being reworked from scratch, no more scaling.
