### ISSUE TITLE
Your SSL certificates have expired

### ISSUE THREAD

**Issue by ktm5j** [negativo17/steam#7]
The SSL certs for negativo17.org have expired and I am unable to install packages because of this.

Can you please renew your cert?  I need to do an OS upgrade and will need to reinstall nvidia/steam etc

**Comment by scaronni** [comment]
After spending a day on the phone with GoDaddy, they informed me that they have an issue with the shared hosting and they can not update certificates on the various instances. According to them they had this issue on the past 3 weeks!

Of course nobody bothered to tell me and now the certificate is expired and I have no way of fixing it. I will move everything to a separate hosting provider as soon as I can, starting from the repositories.

Of course now it will be a dedicated box, so the cost will not be the same. Any donation is of course accepted.
